### ISSUE TITLE
Provide a minimum spec microcontroller recommendation

### ISSUE THREAD

**Issue by sajattack** [charcole/C64Tape#1]
Hi there, I'm wondering what the minimum speed microcontroller would be. Would a 20MHz ATMEGA328 work?

**Comment by charcole** [comment]
I suspect so but I haven't tested it with anything other than the teensy, sorry. If you try it let me know and I can add it to the README.

**Comment by sajattack** [comment]
Ok, and 32K flash should be plenty because we have 9K of source code. Maybe 2K of RAM isn't enough though?

**Comment by charcole** [comment]
Most of the data is stored in an external 128Kb SRAM so shouldn't need too much internal RAM. The LZ compression scheme needs a 1Kb window (stored in internal RAM) but there's not much more than that so 2K of RAM might be enough.

**Comment by sajattack** [comment]
I suppose I might as well just use the [Tapuino Reloaded](https://github.com/arananet/Tapuino-Reloaded) rather than try to roll something with this.
